version: '3.9'

services:
  db:
    image: "postgres:14.1-alpine"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "54321:5432"
    volumes:
      - ./_volumes/db:/var/lib/postgresql/data
    restart: always
